{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "ef51a2ff-260f-4bbc-85e2-b0dee78bebe1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==================== {  File \"<frozen runpy>:198:SB} starts ====================\n",
      "=============== {  File \"<frozen runpy>:198:SB} passed in 19.46s ===============\n",
      "\n",
      "✅ Professional report saved: Dad_IndiaMart_Pro_Report.xlsx\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import time\n",
    "import re\n",
    "from seleniumbase import SB\n",
    "\n",
    "# --- 1. CLEANING FUNCTIONS ---\n",
    "def clean_price(price_str):\n",
    "    try:\n",
    "        clean_str = price_str.replace(',', '')\n",
    "        match = re.search(r'(\\d+(\\.\\d+)?)', clean_str)\n",
    "        return float(match.group(1)) if match else None\n",
    "    except: return None\n",
    "\n",
    "def extract_unit(price_str):\n",
    "    try:\n",
    "        match = re.search(r'/\\s*(\\w+)', price_str)\n",
    "        return match.group(1).strip().capitalize() if match else \"Unit/Request\"\n",
    "    except: return \"N/A\"\n",
    "\n",
    "# --- 2. THE SCRAPER ENGINE ---\n",
    "def run_scraper(query):\n",
    "    with SB(uc=True, headless=True) as sb: # Headless=True for web app feel\n",
    "        url = f\"https://dir.indiamart.com/search.mp?ss={query.replace(' ', '+')}\"\n",
    "        sb.uc_open_with_reconnect(url, reconnect_time=4)\n",
    "        \n",
    "        # Auto-scroll to load products\n",
    "        for _ in range(3):\n",
    "            sb.execute_script(\"window.scrollBy(0, 1000);\")\n",
    "            time.sleep(1)\n",
    "            \n",
    "        listings = []\n",
    "        price_elements = sb.find_elements('//*[contains(text(), \"₹\")]')\n",
    "        \n",
    "        for p in price_elements:\n",
    "            try:\n",
    "                raw_price = p.text.strip()\n",
    "                parent = p.find_element('xpath', './ancestor::div[contains(@class, \"card\") or contains(@class, \"lst\") or contains(@class, \"item\")]')\n",
    "                link_el = parent.find_element('xpath', './/a[contains(@href, \"indiamart.com/proddetail\")]')\n",
    "                \n",
    "                name = link_el.text if link_el.text else \"Product\"\n",
    "                seller = parent.find_element('xpath', './/div[contains(@class, \"comp\")] | .//a[contains(@class, \"ls_nm\")]').text\n",
    "                \n",
    "                try:\n",
    "                    location = parent.find_element('xpath', './/span[contains(@class, \"city\")] | .//span[contains(@class, \"loc\")]').text\n",
    "                except: location = \"Not Specified\"\n",
    "                \n",
    "                listings.append({\n",
    "                    \"Product\": name.strip(),\n",
    "                    \"Price\": raw_price,\n",
    "                    \"Seller\": seller.strip(),\n",
    "                    \"Location\": location.strip(),\n",
    "                    \"Link\": link_el.get_attribute(\"href\")\n",
    "                })\n",
    "            except: continue\n",
    "            \n",
    "        df = pd.DataFrame(listings).drop_duplicates()\n",
    "        if not df.empty:\n",
    "            df['Numeric Price'] = df['Price'].apply(clean_price)\n",
    "            df['Unit'] = df['Price'].apply(extract_unit)\n",
    "            df = df.sort_values(by=['Unit', 'Numeric Price'], ascending=[True, True])\n",
    "        return df\n",
    "\n",
    "# --- 3. STREAMLIT UI ---\n",
    "st.set_page_config(page_title=\"IndiaMart Price Tracker\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📦 IndiaMart Product Comparison Tool\")\n",
    "st.write(f\"Developed for Dad by Aryan | {time.strftime('%Y')}\")\n",
    "\n",
    "# Sidebar Filters\n",
    "with st.sidebar:\n",
    "    st.header(\"Search Settings\")\n",
    "    search_query = st.text_input(\"Enter Product Name:\", placeholder=\"e.g. PVC Pipes\")\n",
    "    search_button = st.button(\"Search & Compare\")\n",
    "    st.info(\"The tool will automatically sort by cheapest price and group by units (Kg/Piece).\")\n",
    "\n",
    "if search_button and search_query:\n",
    "    with st.status(f\"Searching for '{search_query}'...\", expanded=True) as status:\n",
    "        data = run_scraper(search_query)\n",
    "        status.update(label=\"Search Complete!\", state=\"complete\", expanded=False)\n",
    "\n",
    "    if not data.empty:\n",
    "        # Metrics\n",
    "        col1, col2, col3 = st.columns(3)\n",
    "        col1.metric(\"Total Sellers Found\", len(data))\n",
    "        col2.metric(\"Min Price\", f\"₹{data['Numeric Price'].min()}\")\n",
    "        col3.metric(\"Max Price\", f\"₹{data['Numeric Price'].max()}\")\n",
    "\n",
    "        # Searchable Table\n",
    "        st.subheader(\"Results Comparison\")\n",
    "        \n",
    "        # Filtering by Location\n",
    "        locations = [\"All\"] + sorted(data['Location'].unique().tolist())\n",
    "        selected_loc = st.selectbox(\"Filter by City:\", locations)\n",
    "        \n",
    "        filtered_df = data if selected_loc == \"All\" else data[data['Location'] == selected_loc]\n",
    "        \n",
    "        # Display with links\n",
    "        st.dataframe(\n",
    "            filtered_df[['Product', 'Numeric Price', 'Unit', 'Seller', 'Location', 'Link']],\n",
    "            column_config={\n",
    "                \"Link\": st.column_config.LinkColumn(\"Product Link\")\n",
    "            },\n",
    "            use_container_width=True,\n",
    "            hide_index=True\n",
    "        )\n",
    "        \n",
    "        # Download Button\n",
    "        csv = filtered_df.to_csv(index=False).encode('utf-8')\n",
    "        st.download_button(\n",
    "            label=\"📥 Download Data as CSV\",\n",
    "            data=csv,\n",
    "            file_name=f\"indiamart_{search_query.lower()}.csv\",\n",
    "            mime='text/csv',\n",
    "        )\n",
    "    else:\n",
    "        st.error(\"No data found. Please try a different search term or check the logs.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68bd7286-36d6-4354-9c2b-e60a4025a9f9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3b5d905-b126-44eb-ab1d-3dc23ba532c9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4c46160-652e-414c-8fb6-4c63aa17807c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
